name: training joint model test on qanom coarse sweep
method: random
metric:
  name: Labled Arg f1
  goal: maximize
program: run_summarization.py
parameters:
  model_name_or_path:
    value: t5-small
  learning_rate:
    distribution: log_uniform
    max: -2
    min: -10
  dropout_rate:
    distribution: uniform
    max: 0.25
    min: 0.05
  gradient_accumulation_steps:
    distribution: int_uniform
    max: 20
    min: 1
  per_device_train_batch_size:
    value: 12
  seed:
    values:
      - 44
      - 65
      - 32
      - 73
  num_beams:
    distribution: int_uniform
    max: 6
    min: 1
  num_train_epochs:
    distribution: int_uniform
    max: 30
    min: 5
  source_prefix: 
    distribution: categorical
    values: 
      - '<predicate_type> parse:'
      - 'parse <predicate_type>:'
      - 'parse <predicate_type> qas:'
      - 'parse: '

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  # add params
  - '--do_train'
  - '--do_eval'
  - '--report_to' 
  - 'wandb'
  - '--wandb_run_name' 
  - 'qanom joint training sweep coarse' 
  - '--overwrite_output_dir'
  - '--predict_with_generate'
  - '--append_verb_form'
  - '--use_bilateral_predicate_marker'
  - '--fp16'
  - '--load_best_model_at_end'
  - '--do_eval_on' 
  - 'validation'
  - '--save_strategy' 
  - 'steps'
  - '--logging_strategy' 
  - 'steps'
  - '--evaluation_strategy' 
  - 'steps'
  - '--logging_steps' 
  - 500
  - '--eval_steps' 
  - 500
  - '--save_steps' 
  - 500
  - '--metric_for_best_model' 
  - 'eval_loss'
  - '--predicate_marker_type' 
  - 'generic'
  - '--model_type' 
  - 't5'
  - '--preprocess_input_func' 
  - 'input_predicate_marker'
  - '--output_dir' 
  - '/home/nlp/kleinay/tmp/t5-tst-summarization/qanom_joint/qanom_joint_sweep'
  - '--dataset_name' 
  - '{train:14 * biu-nlp/qanom, biu-nlp/qa_srl2018; validation: biu-nlp/qanom; test: biu-nlp/qanom}'
